#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='data_preparation.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat'),
        name='data_preparation'
    )

    ctx(
        features='run_m_script',
        source='simulation_data_preparation.m',
        target=ctx.path_to(ctx, 'OUT_DATA', 'estimation_data.mat'),
        name='estimation_data'
    )
