#! python


def build(ctx):
    ctx(
        features='run_m_script',
        source='Replication_Figure_1_updated.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'Replication_Figure_1_updated.pdf'),
        # deps=[
        #     ctx.path_to(ctx, 'OUT_ANALYSIS', 'schelling_{}.mat'.format(model)),
        #     ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
        # ],
        name='Figure_1_updated'
    )
