#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='replication_figure_1.m',
        target=ctx.path_to(
            ctx, 'OUT_FIGURES', 'figure_1.pdf'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat'),
        ],
        name='figure_1'
    )

    ctx(
        features='run_m_script',
        source='replication_figure_2.m',
        target=[
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'figure_2.pdf'
            )
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'),
        ],
        name='figure_2'
    )

    ctx(
        features='run_m_script',
        source='autocorrelogram.m',
        target=[
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'autocorrelation_tfp.pdf'
            ),
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'autocorrelation_xi.pdf'
            )
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'),
        ],
        name='autocorrelogram'
    )

    ctx(
        features='run_m_script',
        source='table_matrix_a.m',
        target=ctx.path_to(
            ctx, 'OUT_TABLES', 'table_matrix_a.txt'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'),
        ],
        name='table_matrix_a'
    )

    ctx(
        features='run_m_script',
        source='replication_figure_5.m',
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'figure_5.pdf'),
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'baseline_simulation.mat'),
            ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat')
        ],
        name='figure_5'
    )

    ctx(
        features='run_m_script',
        source='replication_table_3.m',
        target=[
            ctx.path_to(ctx, 'OUT_TABLES', 'cal_params.tex'),
            ctx.path_to(ctx, 'OUT_TABLES', 'est_params.tex')
        ],
        deps=ctx.path_to(ctx, 'OUT_ANALYSIS', 'extended_model_results.mat'),
        name='table_3'
    )
