#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='figure_1.m',
        target=ctx.path_to(
            ctx, 'OUT_FIGURES', 'figure_1.pdf'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat'),
        ],
        name='Figure_1'
    )

    ctx(
        features='run_m_script',
        source='figure_2.m',
        target=[
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'figure_2.png'
            )
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'),
        ],
        name='Figure_2'
    )

    ctx(
        features='run_m_script',
        source='autocorrelogram.m',
        target=[
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'autocorrelation_tfp.png'
            ),
            ctx.path_to(
                ctx, 'OUT_FIGURES', 'autocorrelation_xi.png'
            )
        ],
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'),
        ],
        name='Autocorrelogram'
    )
