#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='shock_construction.m',
        target=ctx.path_to(
            ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat'),
        ],
        name='shock_construction'
    )
