#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='shock_construction.m',
        # target=ctx.path_to(
        #     ctx, 'OUT_FIGURES', 'Replication_Figure_1_updated.pdf'
        # ),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'data_shock_construction.mat'),
        ],
        name='shock_construction'
    )
