#! python


def build(ctx):

    ctx(
        features='run_m_script',
        source='shock_construction.m',
        target=ctx.path_to(
            ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_DATA', 'updated_data.mat'),
        ],
        name='shock_construction'
    )

    for model in 'baseline', 'extended':
        # set target and dependency specific to model
        if model == 'baseline':
            target = ctx.path_to(
                ctx, 'OUT_ANALYSIS', '{}_model_results.mat'.format(model)
            )
            deps = []
        else:
            target = []
            deps = ctx.path_to(
                ctx, 'OUT_DATA', 'estimation_data.mat'
            )

        ctx(
            features='run_m_script',
            source=ctx.path_to(
                ctx, 'DYNARE_FILES', 'run_{}_model.m'.format(model)
            ),
            target=target,
            deps=deps,
            name='run_{}_model'.format(model)
        )

    ctx(
        features='run_m_script',
        source='baseline_simulation.m',
        target=ctx.path_to(
            ctx, 'OUT_ANALYSIS', 'baseline_simulation.mat'
        ),
        deps=[
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'baseline_model_results.mat'),
            ctx.path_to(ctx, 'OUT_ANALYSIS', 'series_of_shocks.mat')
        ],
        name='baseline_simulation'
    )
